### PR TITLE
Enable more Aqua tests by solving piracy and ambiguities issues

### LINKED ISSUE #135: Aqua static analysis [$200]
<details>
<summary><strong>Bug bounty logistic details</strong> (click to expand)</summary>

To claim exclusive time to work on this bounty either post a comment here or message [skrastanov@umass.edu](mailto:skrastanov@umass.edu) with:

- your name
- github username
- **(optional)** a brief list of previous pertinent projects you have engaged in

Currently the project is claimed by `no one` until `...`.

If you want to, you can work on this project without making a claim, however claims are encouraged to give you and other contributors peace of mind. Whoever has made a claim takes precedence when solutions are considered.

You can always propose your own funded project, if you would like to contribute something of value that is not yet covered by an official bounty.
</details>

# Project: Aqua static analysis [$200]

We run Aqua.jl static analysis during CI for this library, but currently, we have disabled some checks, as they raise too many errors. This bounty is awarded for fixing these issues and enabling these checks. The bounty might require upstreaming some work from here into QuantumInterface.jl or other packages.

**Required skills**: Generic Julia skills.

**Reviewer**: Stefan Krastanov

**Duration**: 1 month

#### Payout procedure:

The Funding for these bounties comes from the National Science Foundation and from the NSF Center for Quantum Networks. The payouts are managed by the NumFOCUS foundation and processed in bulk once every two months. If you live in a country in which NumFOCUS can make payments, you can participate in this bounty program.

[Click here for more details about the bug bounty program.](https://github.com/QuantumSavory/.github/blob/main/BUG_BOUNTIES.md)

### PR DESCRIPTION
**Pull request by Tortar**
Fixes #135 

This PR is the main contribution to solve #135. But there are some others I will open in other packages, they are required to make everything work. 

It removes all avoidable piracies and all direct ambiguities within the package. As a part of it I also addressed a TODO because otherwise some ambiguities were much difficult to solve: I changed all methods such as `observable(refs::Tuple{Vararg{RegRef, N}}, obs, something=nothing; time)` to `observable(refs::Tuple{Vararg{RegRef, N}}, obs; something=nothing, time=nothing)`, which means that `something` is now a keyword argument of those functions. This is a minor breaking change so maybe it will require a new major version if we want to be strict about it.

### CODE REVIEW

**Comment by Krastanov** [comment]
Thank you, this is very much appreciated! A new breaking release is reasonable for the change you suggested.

**Comment by Tortar** [comment]
I will try to address all formatting problems before you review it because I think that since all PRs are actually dependent from one another it is probably needed that everything is already in place and then you could dev all packages and see if everything works as expected (It should)

**Comment by Tortar** [comment]
I'm not sure if there is a better methodology than this one, let me know if you have suggestions :-)

We will see green at the end of the tunnel

**Comment by Krastanov** [comment]
The SProjector warning in the doc builder is fixed in a separate PR.

Thanks for coordinating all these fixes! I have noted down this bounty and I will be sending you more details on how it will be processed at the end of the month (it will probably be a slow process, as it is managed through a non-profit -- on your end, you will be asked to fill out a form with payment details, but that is all the boilerplate you need to worry about).

**Comment by Tortar** [comment]
Thanks @Krastanov for the help in passing CI tests. 

Do I need to write an email to you at some address to help processing the request?

**Comment by Krastanov** [comment]
Yes, please just send along an email with your name and a link to the bounty. NumFocus will contact you directly to get the transfer information.

**Pull request merged**
